name: CD
on:
  push:
    branches: [ develop, main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/project_manager
            git pull origin ${{ github.ref == 'refs/heads/main' && 'main' || 'develop' }}
            source venv/bin/activate
            pip install -r backend/requirements.txt
            flask db upgrade
            systemctl restart project_manager